#ifndef __EIM_CLIENTAGENT_ERRORS_2014_10_21_BY_YFGZ__
#define __EIM_CLIENTAGENT_ERRORS_2014_10_21_BY_YFGZ__

 ///////////////////////////////////////////////////////////////////////////////
//  HRESULTs are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +-+-+-+-+-+---------------------+-------------------------------+
//  |S|R|C|N|r|    Facility         |               Code            |
//  +-+-+-+-+-+---------------------+-------------------------------+
//  where
//
//      Sev      - is the severity code
//                 00 - Success
//                 01 - Informational
//                 10 - Warning
//                 11 - Error
//
//      C        - is the Customer code flag
//      R        - is a reserved bit
//      Facility - is the facility code
//      Code     - is the facility's status code
// Useful macro for creating our own software exception codes
#ifndef MAKE_SF_EXCEPTION
# define MAKE_SF_EXCEPTION(sev, fac, code) \
   ((HRESULT) ( \
   /* Severity code    */  ( ((unsigned long)(sev))           << 30) |     \
   /* MS(0) or Cust(1) */  ( 1								  << 29) |     \
   /* Reserved(0)      */  ( 0                                << 28) |     \
   /* Facility code    */  ( (((unsigned long)(fac))&0x0fff)  << 16) |     \
   /* Exception code   */  ( (((unsigned long)(code))&0xFFFF) << 0)) )
# endif //MAKE_SF_EXCEPTION

// Severity code

#undef SEVERITY_SUCCESS
#undef SEVERITY_INFO	
#undef SEVERITY_WARNING
#undef SEVERITY_ERROR	

#define	SEVERITY_SUCCESS		0	// Succeess
#define	SEVERITY_INFO			1	// Information
#define	SEVERITY_WARNING		2	// Warning
#define	SEVERITY_ERROR			3	// Error

#define FACILITY_KERNEL			3	// for ClientAgent, DONT MODIFY IT

// No error
#define EIMERR_SUCCESS				(0)
#define EIMERR_INVALID_PARAMTER		(0x80070057L)
#define EIMERR_FAILED				(0x80004005L)

// Information
#define EIMERR_STATUS_ONLINE			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 1)    // Login status: Online
#define EIMERR_STATUS_ONLEAVE			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 2)    // Login status: Onlive
#define EIMERR_STATUS_OFFLINE			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 3)    // Login status: Offline
#define EIMERR_PARSE_FINISHED			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 4)    // Reach at the end of the package, parse finished
#define EIMERR_EMPTY_MSG				MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 5)    // Message is empty
#define EIMERR_STATUS_LOGINING			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 6)    // Logining
#define EIMERR_REPEAT_NOTICE			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 7)    // Repeat notice
#define EIMERR_DOWNLOADING_DB			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 8)    //  
#define EIMERR_UPDATE_DEPT				MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 9)    //  
#define EIMERR_UPDATE_DEPT_OK			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 10)    //  
#define EIMERR_UPDATE_EMP				MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 11)    //  
#define EIMERR_UPDATE_EMP_OK			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 12)    //  
#define EIMERR_UPDATE_DEPTEMP			MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 13)    //  
#define EIMERR_UPDATE_DEPTEMP_OK		MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 14)    //  
#define EIMERR_LOAD_EMP					MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 15)    //  
#define EIMERR_LOAD_EMP_OK				MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 16)    //  
#define EIMERR_LOAD_DEPT				MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 17)    //  
#define EIMERR_LOAD_DEPT_OK				MAKE_SF_EXCEPTION(SEVERITY_INFO, FACILITY_KERNEL, 18)    //  

// RESULT
#define EIMERR_NOT_LOGIN				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 1)   // Not login
#define EIMERR_REPEAT_LOGIN				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 2)   // Repeat login
#define EIMERR_INVALID_PSW				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 3)   // Password error
#define EIMERR_INVALIDUSER				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 4)   // Invalid user
#define EIMERR_REQ_TIMEOUT				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 5)   // Request timeout
#define EIMERR_NO_GROUP 				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 6)   // Not exist group
#define EIMERR_MSGLEN_OVERLOAD			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 7)   // Message too long
#define EIMERR_UNKNOWNS					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 8)   // Unknown error
#define EIMERR_NO_REGULAR_GROUP			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 9)   // Not exist regular group
#define EIMERR_GROUP_EXISTED			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 10)  // Group already existed
#define EIMERR_CREATE_GROUP_FAIL		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 11)  // Create group failed
#define EIMERR_FORBIDDEN				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 12)  // Forbidden operate
#define EIMERR_INCALIDREQ  				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 13)  // Invalid request

#define EIMERR_SYSTEM_OVERLOAD			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 14)  // 超过整体过载保护（200条/秒） 
#define EIMERR_SYSTEM_MAX_CONNECT		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 15)  // 系统达到最大连接数
#define EIMERR_USER_IN_BLACKLIST		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 16)  // 用户在黑名单中（停止尝试登录）
#define EIMERR_VERSION_TOO_LITTLE		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 17)  // 客户端版本过低(强制升级且是移动端才提示)

#define EIMERR_CONNECT_SSO				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 18)  // 系统达到最大连接数
#define EIMERR_SSO_AD_NOFOUND			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 19)  // 系统达到最大连接数
#define EIMERR_SSO_DB_NOFOUND			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 20)  // 系统达到最大连接数
#define EIMERR_SSO_SET_AD_PSW			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 21)  // 系统达到最大连接数
#define EIMERR_SSO_SET_DB_PSW			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 22)  // 系统达到最大连接数
#define EIMERR_SSO_SET_RTX_PSW			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 23)  // 系统达到最大连接数
#define EIMERR_SSO_SET_NC_PSW			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 24)  // 系统达到最大连接数
#define EIMERR_SSO_VISIT_AD				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 25)  // 系统达到最大连接数
#define EIMERR_SSO_ORI_PSW				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 26)  // 系统达到最大连接数
#define EIMERR_SSO_IDENTITY				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 27)  // 系统达到最大连接数
#define EIMERR_SSO_CALL					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 28)  // 系统达到最大连接数
#define EIMERR_SSO_NOMEMORY				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 29)  // 系统达到最大连接数
#define EIMERR_SSO_CONNECT_AD			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 30)  // 系统达到最大连接数
#define EIMERR_SSO_UPDATE_AD			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 31)  // 系统达到最大连接数
#define EIMERR_SSO_OTHER				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 32)  // 系统达到最大连接数
#define EIMERR_SSO_USER_OR_PSW			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 33)  // 系统达到最大连接数
#define EIMERR_SSO_USER_FORBID			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 34)  // 系统达到最大连接数
#define EIMERR_SSO_USER_EXPIRE			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 35)  // 系统达到最大连接数
#define EIMERR_SSO_USER_ORIGINALPSW		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 36)  // 系统达到最大连接数
#define EIMERR_SSO_PSW_EXPIRE_NEXT_SET	MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 37)  // 系统达到最大连接数
#define EIMERR_SSO_PSW_EXPIRE			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 38)  // 系统达到最大连接数
#define EIMERR_SSO_NO_VISIT_POWER		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 39)  // 系统达到最大连接数
#define EIMERR_SSO_IP_ILLEGAL			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 40)  // 系统达到最大连接数
#define EIMERR_SSO_USER_OR_PSW_EMPTY	MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 41)  // 系统达到最大连接数
#define EIMERR_SSO_SYSCODE_EMPTY		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 42)  // 系统达到最大连接数
#define EIMERR_SSO_HTTP_GET_FORBID		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 43)  // 系统达到最大连接数
#define EIMERR_SSO_HTTP_POST_FORBID		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 44)  // 系统达到最大连接数
#define EIMERR_SSO_HTTP_CONTENTTYPE		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 45)  // 系统达到最大连接数
#define EIMERR_SSO_FUNCTION_FORBID		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 46)  // 系统达到最大连接数

#define EIMERR_VIRGTOUP_NOT_EXIT        MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 47)  //Virtual group is not exist
#define EIMERR_VIRGTOUP_OUTOF_SVC       MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 48)  //Virtual group is out of service
#define EIMERR_VIRGROUP_SVC_DENIED      MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 49)  //Virtual group can not reply msg
#define EIMERR_CREATE_GROUP_VIRGROUP    MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 50)  //Group Can Not Contain Virgroup

// 
#define EIMERR_NO_USER					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 51)  // No User
#define EIMERR_CONN_TIMEOUT				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 54)  // Time out
#define EIMERR_CONN_FAILED				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 55)  // Connect failed
#define EIMERR_NOT_CONN					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 56)  // Not connect
#define EIMERR_SOCKETSETOPT				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 57)  // Not connect
#define EIMERR_KICK						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 58)  // Kicked
#define EIMERR_INIT_FAILED				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 59)  // Initial Failed
#define EIMERR_NO_RSA_KEY				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 60)  // RSA public key not found
#define EIMERR_CONNECT_ERROR			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 69)  // Connect error
#define EIMERR_GROUP_OVERLOAD			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 60)  // The number of members of the group over the limit
#define EIMERR_OVER_SIZE				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 61)  // Message over size 
#define EIMERR_RECVER_OVERLOAD			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 62)  // The receiver number over 
#define EIMERR_TITLE_LEN_OVERLOAD		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 63)  // Title too long
#define EIMERR_PACKAGE_ERROR			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 64)  // Package error
//
#define EIMERR_RECV_TIMEOUT_SOCKET				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 99)  // Timeout
#define EIMERR_SOCKETFD_SOCKET					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 100) // Socket bad fd
#define EIMERR_RECVDATA_TOOBIG_SOCKET			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 101) // Receive data too big
#define EIMERR_RSAKEY_SOCKET					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 102) // RSAKEY error
#define EIMERR_OPENRSAFILE_SOCKET				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 103) // open public rsa file failed
#define EIMERR_RECVSOCKET_SOCKET				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 104) // receive error
#define EIMERR_SOCKETCLOSE_SOCKET				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 105) // socket closed
#define EIMERR_SENDSOCKET_EWOULDBLOCK_SOCKET	MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 106) // send socket error
#define EIMERR_SENDSOCKET_SOCKET				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 107) // send socket again error
#define EIMERR_RECVMSG_TIMEOUT_SOCKET			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 108) // recv socket timeout
#define EIMERR_CONNCB_SOCKET					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 109) // ConnCB error
#define EIMERR_GETHOSTNAME_SOCKET				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 110) // Get host name fail
#define EIMERR_CONNECT_TIMEOUT_SOCKET			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 111) // Conn access manager service timeout error
#define EIMERR_SOCKET_GETOPT_SOCKET				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 112) // getsockopt error
#define EIMERR_SOCKET_OTHERS_ERR				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 113) // Other socket error
#define EIMERR_GETHOSTNAME_SERVICE_SOCKET		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 114) // Conn timeout error
#define EIMERR_CONNECT_SERVICE_TIMEOUT_SOCKET	MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 115) // connect in service timeout
#define EIMERR_RECV_DATA_SOCKET					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 116) // recv exception
#define EIMERR_ACCESS_MANAGER_FAIL				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 150) // Acces manager fail
#define EIMERR_ACCESS_MANAGER_FAIL_ERR			MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 151) // 接入管理错误
#define EIMERR_ACCESS_MANAGER_OVERLOAD_ERR		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 152) // 接入管理过载保护
#define EIMERR_ACCESS_MANAGER_BLACKUSER_ERR		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 153) // 接入管理黑名单 
#define EIMERR_ALIVE_NO_CONNECT					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 170) // 无连接
#define EIMERR_ALIVE_NO_LOGIN					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 171) // Not login
#define EIMERR_FUNCTION_PARAM_MAXVALUE_ERR		MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 181) // 函数参数超过最大值
#define EIMERR_LOGIN_OVERTIME					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_KERNEL, 213) // 登录超时


#endif  // __EIM_CLIENTAGENT_ERRORS_2014_10_21_BY_YFGZ__